# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::AccountService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::AccountService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  METHOD_TABLE = [
    { name: :batch_set_collateral, path: '/v5/account/set-collateral-switch-batch', method: :post, signed: true },
    { name: :get_borrow_history, path: '/v5/account/borrow-history', method: :get, signed: true },
    { name: :get_collateral_info, path: '/v5/account/collateral-info', method: :get, signed: true },
    { name: :get_dcp_info, path: '/v5/account/query-dcp-info', method: :get, signed: true },
    { name: :get_fee_rate, path: '/v5/account/fee-rate', method: :get, signed: true },
    { name: :get_info, path: '/v5/account/info', method: :get, signed: true },
    { name: :get_instruments, path: '/v5/account/instruments-info', method: :get, signed: true },
    { name: :get_mmp_state, path: '/v5/account/mmp-state', method: :get, signed: true },
    { name: :get_smp_group, path: '/v5/account/smp-group', method: :get, signed: true },
    { name: :get_transaction_log, path: '/v5/account/transaction-log', method: :get, signed: true },
    { name: :get_transferable_amount, path: '/v5/account/withdrawal', method: :get, signed: true },
    { name: :get_user_settings, path: '/v5/account/user-setting-config', method: :get, signed: true },
    { name: :manual_borrow, path: '/v5/account/borrow', method: :post, signed: true },
    { name: :manual_repay, path: '/v5/account/repay', method: :post, signed: true },
    { name: :no_convert_repay, path: '/v5/account/no-convert-repay', method: :post, signed: true },
    { name: :one_click_repay, path: '/v5/account/quick-repayment', method: :post, signed: true },
    { name: :reset_mmp, path: '/v5/account/mmp-reset', method: :post, signed: true },
    { name: :set_collateral_coin, path: '/v5/account/set-collateral-switch', method: :post, signed: true },
    { name: :set_margin_mode, path: '/v5/account/set-margin-mode', method: :post, signed: true },
    { name: :set_mmp, path: '/v5/account/mmp-modify', method: :post, signed: true },
    { name: :set_price_limit, path: '/v5/account/set-limit-px-action', method: :post, signed: true },
    { name: :set_spot_hedging, path: '/v5/account/set-hedging-mode', method: :post, signed: true },
    { name: :upgrade_to_uta_pro, path: '/v5/account/upgrade-to-uta', method: :post, signed: true },
  ].freeze

  METHOD_TABLE.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
