# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::AssetService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::AssetService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  METHOD_TABLE = [
    { name: :account_coin_balance_query, path: '/v5/asset/transfer/query-account-coin-balance', method: :get, signed: true },
    { name: :asset_info_query, path: '/v5/asset/transfer/query-asset-info', method: :get, signed: true },
    { name: :cancel_withdraw, path: '/v5/asset/withdraw/cancel', method: :post, signed: true },
    { name: :coin_convert_limit_query, path: '/v5/asset/exchange/query-convert-limit', method: :get, signed: true },
    { name: :coin_list_query, path: '/v5/asset/exchange/query-coin-list', method: :get, signed: true },
    { name: :convert_execute, path: '/v5/asset/exchange/convert-execute', method: :post, signed: true },
    { name: :convert_history_query, path: '/v5/asset/exchange/query-convert-history', method: :get, signed: true },
    { name: :get_asset_overview, path: '/v5/asset/asset-overview', method: :get, signed: true },
    { name: :get_coin_balance, path: '/v5/asset/transfer/query-account-coins-balance', method: :get, signed: true },
    { name: :get_coin_greeks, path: '/v5/asset/coin-greeks', method: :get, signed: true },
    { name: :get_coin_info, path: '/v5/asset/coin/query-info', method: :get, signed: true },
    { name: :get_convert_result, path: '/v5/asset/exchange/convert-result-query', method: :get, signed: true },
    { name: :get_delivery_record, path: '/v5/asset/delivery-record', method: :get, signed: true },
    { name: :get_deposit_address, path: '/v5/asset/deposit/query-address', method: :get, signed: true },
    { name: :get_portfolio_margin, path: '/v5/asset/portfolio-margin', method: :get, signed: true },
    { name: :get_settlement_record, path: '/v5/asset/settlement-record', method: :get, signed: true },
    { name: :get_sub_member_deposit_address, path: '/v5/asset/deposit/query-sub-member-address', method: :get, signed: true },
    { name: :get_total_members_assets, path: '/v5/asset/total-members-assets', method: :get, signed: true },
    { name: :get_vasp_list, path: '/v5/asset/withdraw/vasp/list', method: :get, signed: true },
    { name: :get_withdrawable_amount_by_coin, path: '/v5/asset/withdraw/withdrawable-amount', method: :get, signed: true },
    { name: :inter_transfer, path: '/v5/asset/transfer/inter-transfer', method: :post, signed: true },
    { name: :inter_transfer_list_query, path: '/v5/asset/transfer/query-inter-transfer-list', method: :get, signed: true },
    { name: :list_convert_orders, path: '/v5/asset/exchange/query-order-list', method: :get, signed: true },
    { name: :list_convert_orders_by_page, path: '/v5/asset/exchange/order-record', method: :get, signed: true },
    { name: :list_deposit_records, path: '/v5/asset/deposit/query-record', method: :get, signed: true },
    { name: :list_funding_history, path: '/v5/asset/fundinghistory', method: :get, signed: true },
    { name: :list_internal_deposit_records, path: '/v5/asset/deposit/query-internal-record', method: :get, signed: true },
    { name: :list_small_balance_coins, path: '/v5/asset/covert/small-balance-list', method: :get, signed: true },
    { name: :list_small_balance_history, path: '/v5/asset/covert/small-balance-history', method: :get, signed: true },
    { name: :list_sub_member_deposit_records, path: '/v5/asset/deposit/query-sub-member-record', method: :get, signed: true },
    { name: :list_withdraw_addresses, path: '/v5/asset/withdraw/query-address', method: :get, signed: true },
    { name: :list_withdraw_records, path: '/v5/asset/withdraw/query-record', method: :get, signed: true },
    { name: :quote_apply, path: '/v5/asset/exchange/quote-apply', method: :post, signed: true },
    { name: :send_withdraw, path: '/v5/asset/withdraw/create', method: :post, signed: true },
    { name: :set_default_deposit_to_account, path: '/v5/asset/deposit/deposit-to-account', method: :post, signed: true },
    { name: :small_asset_convert, path: '/v5/asset/covert/small-balance-execute', method: :post, signed: true },
    { name: :small_asset_quote, path: '/v5/asset/covert/get-quote', method: :post, signed: true },
    { name: :sub_member_list_query, path: '/v5/asset/transfer/query-sub-member-list', method: :get, signed: true },
    { name: :transfer_coin_list_query, path: '/v5/asset/transfer/query-transfer-coin-list', method: :get, signed: true },
    { name: :transfer_sub_member_save, path: '/v5/asset/transfer/save-transfer-sub-member', method: :post, signed: true },
    { name: :universal_transfer, path: '/v5/asset/transfer/universal-transfer', method: :post, signed: true },
    { name: :universal_transfer_list_query, path: '/v5/asset/transfer/query-universal-transfer-list', method: :get, signed: true },
  ].freeze

  METHOD_TABLE.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
