# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::BotService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::BotService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  METHOD_TABLE = [
    { name: :close_combo_bot, path: '/v5/fcombobot/close', method: :post, signed: true },
    { name: :close_dca_bot, path: '/v5/dca/close-bot', method: :post, signed: true },
    { name: :close_futures_grid_bot, path: '/v5/fgridbot/close', method: :post, signed: true },
    { name: :close_futures_martingale_bot, path: '/v5/fmartingalebot/close', method: :post, signed: true },
    { name: :close_grid_bot, path: '/v5/grid/close-grid', method: :post, signed: true },
    { name: :create_combo_bot, path: '/v5/fcombobot/create', method: :post, signed: true },
    { name: :create_dca_bot, path: '/v5/dca/create-bot', method: :post, signed: true },
    { name: :create_futures_grid_bot, path: '/v5/fgridbot/create', method: :post, signed: true },
    { name: :create_futures_martingale_bot, path: '/v5/fmartingalebot/create', method: :post, signed: true },
    { name: :create_grid_bot, path: '/v5/grid/create-grid', method: :post, signed: true },
    { name: :get_combo_detail, path: '/v5/fcombobot/detail', method: :post, signed: true },
    { name: :get_combo_limit, path: '/v5/fcombobot/getlimit', method: :post, signed: true },
    { name: :get_futures_grid_detail, path: '/v5/fgridbot/detail', method: :post, signed: true },
    { name: :get_futures_martingale_detail, path: '/v5/fmartingalebot/detail', method: :post, signed: true },
    { name: :get_futures_martingale_limit, path: '/v5/fmartingalebot/getlimit', method: :post, signed: true },
    { name: :get_grid_detail, path: '/v5/grid/query-grid-detail', method: :post, signed: true },
    { name: :validate_futures_grid_input, path: '/v5/fgridbot/validate', method: :post, signed: true },
    { name: :validate_grid_input, path: '/v5/grid/validate-input', method: :post, signed: true },
  ].freeze

  METHOD_TABLE.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
