# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::BrokerService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::BrokerService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  method_table = [
    { name: :distribute_award, path: '/v5/broker/award/distribute-award', method: :post, signed: true },
    { name: :get_award_info, path: '/v5/broker/award/info', method: :post, signed: true },
    { name: :get_broker_account_info, path: '/v5/broker/account-info', method: :get, signed: true },
    { name: :get_broker_rate_limit_cap, path: '/v5/broker/apilimit/query-cap', method: :get, signed: true },
    { name: :get_distribution_record, path: '/v5/broker/award/distribution-record', method: :post, signed: true },
    { name: :list_broker_earnings, path: '/v5/broker/earnings-info', method: :get, signed: true },
    { name: :list_broker_sub_uids, path: '/v5/broker/apilimit/query-all', method: :get, signed: true },
    { name: :set_api_limit, path: '/v5/broker/apilimit/set', method: :post, signed: true },
  ].freeze

  method_table.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
