# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::CryptoLoanService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::CryptoLoanService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  method_table = [
    { name: :adjust_ltv, path: '/v5/crypto-loan-common/adjust-ltv', method: :post, signed: true },
    { name: :borrow_fixed, path: '/v5/crypto-loan-fixed/borrow', method: :post, signed: true },
    { name: :borrow_flexible, path: '/v5/crypto-loan-flexible/borrow', method: :post, signed: true },
    { name: :cancel_fixed_borrow_order, path: '/v5/crypto-loan-fixed/borrow-order-cancel', method: :post, signed: true },
    { name: :cancel_fixed_supply_order, path: '/v5/crypto-loan-fixed/supply-order-cancel', method: :post, signed: true },
    { name: :get_adjustment_history, path: '/v5/crypto-loan-common/adjustment-history', method: :get, signed: true },
    { name: :get_collateral_data, path: '/v5/crypto-loan-common/collateral-data', method: :get, signed: false },
    { name: :get_fixed_borrow_contract_info, path: '/v5/crypto-loan-fixed/borrow-contract-info', method: :get, signed: true },
    { name: :get_fixed_borrow_order_info, path: '/v5/crypto-loan-fixed/borrow-order-info', method: :get, signed: true },
    { name: :get_fixed_borrow_order_quote, path: '/v5/crypto-loan-fixed/borrow-order-quote', method: :get, signed: false },
    { name: :get_fixed_renew_info, path: '/v5/crypto-loan-fixed/renew-info', method: :get, signed: true },
    { name: :get_fixed_supply_contract_info, path: '/v5/crypto-loan-fixed/supply-contract-info', method: :get, signed: true },
    { name: :get_fixed_supply_order_info, path: '/v5/crypto-loan-fixed/supply-order-info', method: :get, signed: true },
    { name: :get_fixed_supply_order_quote, path: '/v5/crypto-loan-fixed/supply-order-quote', method: :get, signed: false },
    { name: :get_flexible_borrow_history, path: '/v5/crypto-loan-flexible/borrow-history', method: :get, signed: true },
    { name: :get_flexible_ongoing_coin, path: '/v5/crypto-loan-flexible/ongoing-coin', method: :get, signed: true },
    { name: :get_flexible_repayment_history, path: '/v5/crypto-loan-flexible/repayment-history', method: :get, signed: true },
    { name: :get_loanable_data, path: '/v5/crypto-loan-common/loanable-data', method: :get, signed: true },
    { name: :get_max_collateral_amount, path: '/v5/crypto-loan-common/max-collateral-amount', method: :get, signed: true },
    { name: :get_max_loan, path: '/v5/crypto-loan-common/max-loan', method: :post, signed: true },
    { name: :get_position, path: '/v5/crypto-loan-common/position', method: :get, signed: true },
    { name: :renew_fixed, path: '/v5/crypto-loan-fixed/renew', method: :post, signed: true },
    { name: :repay_fixed_fully, path: '/v5/crypto-loan-fixed/fully-repay', method: :post, signed: true },
    { name: :repay_fixed_with_collateral, path: '/v5/crypto-loan-fixed/repay-collateral', method: :post, signed: true },
    { name: :repay_flexible, path: '/v5/crypto-loan-flexible/repay', method: :post, signed: true },
    { name: :repay_flexible_with_collateral, path: '/v5/crypto-loan-flexible/repay-collateral', method: :post, signed: true },
  ].freeze

  method_table.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
