# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::EarnService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::EarnService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  method_table = [
    { name: :add_liquidity, path: '/v5/earn/liquidity-mining/add-liquidity', method: :post, signed: true },
    { name: :add_margin, path: '/v5/earn/liquidity-mining/add-margin', method: :post, signed: true },
    { name: :claim_liquidity_interest, path: '/v5/earn/liquidity-mining/claim-interest', method: :post, signed: true },
    { name: :get_advance_earn_order, path: '/v5/earn/advance/order', method: :get, signed: true },
    { name: :get_advance_earn_position, path: '/v5/earn/advance/position', method: :get, signed: true },
    { name: :get_advance_earn_product, path: '/v5/earn/advance/product', method: :get, signed: false },
    { name: :get_advance_earn_product_extra_info, path: '/v5/earn/advance/product-extra-info', method: :get, signed: false },
    { name: :get_apr_history, path: '/v5/earn/apr-history', method: :get, signed: false },
    { name: :get_double_win_leverage, path: '/v5/earn/advance/double-win-leverage', method: :get, signed: true },
    { name: :get_fixed_term_order, path: '/v5/earn/fixed-term/order', method: :get, signed: true },
    { name: :get_fixed_term_position, path: '/v5/earn/fixed-term/position', method: :get, signed: true },
    { name: :get_fixed_term_product, path: '/v5/earn/fixed-term/product', method: :get, signed: false },
    { name: :get_hold_to_earn_product, path: '/v5/earn/hold-to-earn/product', method: :get, signed: false },
    { name: :get_hold_to_earn_yield_history, path: '/v5/earn/hold-to-earn/yield-history', method: :get, signed: true },
    { name: :get_hourly_yield_history, path: '/v5/earn/hourly-yield', method: :get, signed: true },
    { name: :get_liquidity_mining_liquidation_records, path: '/v5/earn/liquidity-mining/liquidation-records', method: :get, signed: true },
    { name: :get_liquidity_mining_orders, path: '/v5/earn/liquidity-mining/order', method: :get, signed: true },
    { name: :get_liquidity_mining_positions, path: '/v5/earn/liquidity-mining/position', method: :get, signed: true },
    { name: :get_liquidity_mining_products, path: '/v5/earn/liquidity-mining/product', method: :get, signed: false },
    { name: :get_liquidity_mining_yield_records, path: '/v5/earn/liquidity-mining/yield-records', method: :get, signed: true },
    { name: :get_order_history, path: '/v5/earn/order', method: :get, signed: true },
    { name: :get_position, path: '/v5/earn/position', method: :get, signed: true },
    { name: :get_product, path: '/v5/earn/product', method: :get, signed: false },
    { name: :get_rwa_nav_chart, path: '/v5/earn/rwa/nav-chart', method: :get, signed: false },
    { name: :get_rwa_order_list, path: '/v5/earn/rwa/order', method: :get, signed: true },
    { name: :get_rwa_position_list, path: '/v5/earn/rwa/position', method: :get, signed: true },
    { name: :get_rwa_product_list, path: '/v5/earn/rwa/product', method: :get, signed: false },
    { name: :get_smart_leverage_redeem_est_amount_list, path: '/v5/earn/advance/get-redeem-est-amount-list', method: :get, signed: true },
    { name: :get_token_daily_yield, path: '/v5/earn/token/yield', method: :get, signed: true },
    { name: :get_token_historical_apr, path: '/v5/earn/token/history-apr', method: :get, signed: false },
    { name: :get_token_hourly_yield, path: '/v5/earn/token/hourly-yield', method: :get, signed: true },
    { name: :get_token_order_list, path: '/v5/earn/token/order', method: :get, signed: true },
    { name: :get_token_position, path: '/v5/earn/token/position', method: :get, signed: true },
    { name: :get_token_product, path: '/v5/earn/token/product', method: :get, signed: false },
    { name: :get_yield_history, path: '/v5/earn/yield', method: :get, signed: true },
    { name: :list_coupons, path: '/v5/earn/coupons', method: :get, signed: true },
    { name: :modify_earn_position, path: '/v5/earn/position/modify', method: :post, signed: true },
    { name: :place_advance_earn_order, path: '/v5/earn/advance/place-order', method: :post, signed: true },
    { name: :place_fixed_term_order, path: '/v5/earn/fixed-term/place-order', method: :post, signed: true },
    { name: :place_order, path: '/v5/earn/place-order', method: :post, signed: true },
    { name: :place_rwa_order, path: '/v5/earn/rwa/place-order', method: :post, signed: true },
    { name: :place_token_order, path: '/v5/earn/token/place-order', method: :post, signed: true },
    { name: :pwm_asset_trend, path: '/v5/earn/pwm/investment-plan/asset-trend', method: :get, signed: true },
    { name: :pwm_claim, path: '/v5/earn/pwm/investment-plan/claim', method: :post, signed: true },
    { name: :pwm_create_custom_plan, path: '/v5/earn/pwm/customize-plan/create', method: :post, signed: true },
    { name: :pwm_fund_nav, path: '/v5/earn/pwm/investment-plan/fund-nav', method: :get, signed: true },
    { name: :pwm_fund_transfer, path: '/v5/earn/pwm/fund-transfer', method: :post, signed: true },
    { name: :pwm_get_new_plan_detail, path: '/v5/earn/pwm/investment-plan/new-plan', method: :get, signed: true },
    { name: :pwm_get_plan_detail, path: '/v5/earn/pwm/investment-plan/detail', method: :get, signed: true },
    { name: :pwm_inst_create_fund, path: '/v5/earn/pwm/asset-manager/create-fund', method: :post, signed: true },
    { name: :pwm_inst_create_investment_plan, path: '/v5/earn/pwm/asset-manager/create-investment-plan', method: :post, signed: true },
    { name: :pwm_inst_create_sub_account, path: '/v5/earn/pwm/asset-manager/create-sub-account', method: :post, signed: true },
    { name: :pwm_inst_get_investment_plans, path: '/v5/earn/pwm/asset-manager/get-investment-plan', method: :get, signed: true },
    { name: :pwm_inst_list_funds, path: '/v5/earn/pwm/asset-manager/all-funds', method: :get, signed: true },
    { name: :pwm_inst_list_orders, path: '/v5/earn/pwm/asset-manager/all-order', method: :get, signed: true },
    { name: :pwm_inst_manage_investment_plan, path: '/v5/earn/pwm/asset-manager/manage-investment-plan', method: :post, signed: true },
    { name: :pwm_inst_manage_order, path: '/v5/earn/pwm/asset-manager/manage-order', method: :post, signed: true },
    { name: :pwm_inst_settle_profit, path: '/v5/earn/pwm/asset-manager/settle-profit', method: :post, signed: true },
    { name: :pwm_invest_more, path: '/v5/earn/pwm/investment-plan/invest-more', method: :post, signed: true },
    { name: :pwm_list_investment_plans, path: '/v5/earn/pwm/investment-plan/all', method: :get, signed: true },
    { name: :pwm_list_order, path: '/v5/earn/pwm/investment-plan/order', method: :get, signed: true },
    { name: :pwm_list_product_cards, path: '/v5/earn/pwm/customize-plan/product', method: :get, signed: false },
    { name: :pwm_query_fund_transfer_result, path: '/v5/earn/pwm/query-fund-transfer-result', method: :get, signed: true },
    { name: :pwm_redeem, path: '/v5/earn/pwm/investment-plan/redeem', method: :post, signed: true },
    { name: :pwm_subscribe, path: '/v5/earn/pwm/investment-plan/subscribe', method: :post, signed: true },
    { name: :redeem_fixed_term, path: '/v5/earn/fixed-term/redeem', method: :post, signed: true },
    { name: :reinvest_liquidity, path: '/v5/earn/liquidity-mining/reinvest', method: :post, signed: true },
    { name: :remove_liquidity, path: '/v5/earn/liquidity-mining/remove-liquidity', method: :post, signed: true },
    { name: :set_fixed_term_auto_invest, path: '/v5/earn/fixed-term/position/auto-invest', method: :post, signed: true },
  ].freeze

  method_table.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
