# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::MarketService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::MarketService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  METHOD_TABLE = [
    { name: :get_adl_alert, path: '/v5/market/adlalert', method: :get, signed: false },
    { name: :get_delivery_price, path: '/v5/market/delivery-price', method: :get, signed: false },
    { name: :get_fee_group_info, path: '/v5/market/fee-group-info', method: :get, signed: false },
    { name: :get_funding_rate_history, path: '/v5/market/funding/history', method: :get, signed: false },
    { name: :get_historical_volatility, path: '/v5/market/historical-volatility', method: :get, signed: false },
    { name: :get_index_price_components, path: '/v5/market/index-price-components', method: :get, signed: false },
    { name: :get_index_price_kline, path: '/v5/market/index-price-kline', method: :get, signed: false },
    { name: :get_instruments_info, path: '/v5/market/instruments-info', method: :get, signed: false },
    { name: :get_insurance_pool, path: '/v5/market/insurance', method: :get, signed: false },
    { name: :get_kline, path: '/v5/market/kline', method: :get, signed: false },
    { name: :get_long_short_ratio, path: '/v5/market/account-ratio', method: :get, signed: false },
    { name: :get_mark_price_kline, path: '/v5/market/mark-price-kline', method: :get, signed: false },
    { name: :get_new_delivery_price, path: '/v5/market/new-delivery-price', method: :get, signed: false },
    { name: :get_open_interest, path: '/v5/market/open-interest', method: :get, signed: false },
    { name: :get_order_price_limit, path: '/v5/market/price-limit', method: :get, signed: false },
    { name: :get_orderbook, path: '/v5/market/orderbook', method: :get, signed: false },
    { name: :get_premium_index_price_kline, path: '/v5/market/premium-index-price-kline', method: :get, signed: false },
    { name: :get_recent_public_trades, path: '/v5/market/recent-trade', method: :get, signed: false },
    { name: :get_risk_limit, path: '/v5/market/risk-limit', method: :get, signed: false },
    { name: :get_rpi_orderbook, path: '/v5/market/rpi_orderbook', method: :get, signed: false },
    { name: :get_server_time, path: '/v5/market/time', method: :get, signed: false },
    { name: :get_tickers, path: '/v5/market/tickers', method: :get, signed: false },
  ].freeze

  METHOD_TABLE.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
