# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::P2pService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::P2pService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  method_table = [
    { name: :create_ad, path: '/v5/p2p/item/create', method: :post, signed: true },
    { name: :get_account_info, path: '/v5/p2p/user/personal/info', method: :post, signed: true },
    { name: :get_ads, path: '/v5/p2p/item/online', method: :post, signed: true },
    { name: :get_all_orders, path: '/v5/p2p/order/simplifyList', method: :post, signed: true },
    { name: :get_chat_messages, path: '/v5/p2p/order/message/listpage', method: :post, signed: true },
    { name: :get_counterparty_user_info, path: '/v5/p2p/user/order/personal/info', method: :post, signed: true },
    { name: :get_my_ad_details, path: '/v5/p2p/item/info', method: :post, signed: true },
    { name: :get_my_ads, path: '/v5/p2p/item/personal/list', method: :post, signed: true },
    { name: :get_order_detail, path: '/v5/p2p/order/info', method: :post, signed: true },
    { name: :get_pending_orders, path: '/v5/p2p/order/pending/simplifyList', method: :post, signed: true },
    { name: :get_user_payment, path: '/v5/p2p/user/payment/list', method: :post, signed: true },
    { name: :mark_order_as_paid, path: '/v5/p2p/order/pay', method: :post, signed: true },
    { name: :release_assets, path: '/v5/p2p/order/finish', method: :post, signed: true },
    { name: :remove_ad, path: '/v5/p2p/item/cancel', method: :post, signed: true },
    { name: :send_chat_message, path: '/v5/p2p/order/message/send', method: :post, signed: true },
    { name: :update_ad, path: '/v5/p2p/item/update', method: :post, signed: true },
    { name: :upload_chat_file, path: '/v5/p2p/oss/upload_file', method: :post, signed: true },
  ].freeze

  method_table.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
