# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::PositionService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::PositionService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  METHOD_TABLE = [
    { name: :add_reduce_margin, path: '/v5/position/add-margin', method: :post, signed: true },
    { name: :confirm_new_risk_limit, path: '/v5/position/confirm-pending-mmr', method: :post, signed: true },
    { name: :get_closed_pnl, path: '/v5/position/closed-pnl', method: :get, signed: true },
    { name: :get_closed_positions, path: '/v5/position/get-closed-positions', method: :get, signed: true },
    { name: :get_move_position_history, path: '/v5/position/move-history', method: :get, signed: true },
    { name: :get_positions, path: '/v5/position/list', method: :get, signed: true },
    { name: :move_position, path: '/v5/position/move-positions', method: :post, signed: true },
    { name: :set_auto_add_margin, path: '/v5/position/set-auto-add-margin', method: :post, signed: true },
    { name: :set_leverage, path: '/v5/position/set-leverage', method: :post, signed: true },
    { name: :set_trading_stop, path: '/v5/position/trading-stop', method: :post, signed: true },
    { name: :switch_position_mode, path: '/v5/position/switch-mode', method: :post, signed: true },
  ].freeze

  METHOD_TABLE.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
