# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::RfqService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::RfqService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  method_table = [
    { name: :accept_non_lp_quote, path: '/v5/rfq/accept-other-quote', method: :post, signed: true },
    { name: :cancel_all_quotes, path: '/v5/rfq/cancel-all-quotes', method: :post, signed: true },
    { name: :cancel_all_rfqs, path: '/v5/rfq/cancel-all-rfq', method: :post, signed: true },
    { name: :cancel_quote, path: '/v5/rfq/cancel-quote', method: :post, signed: true },
    { name: :cancel_rfq, path: '/v5/rfq/cancel-rfq', method: :post, signed: true },
    { name: :create_quote, path: '/v5/rfq/create-quote', method: :post, signed: true },
    { name: :create_rfq, path: '/v5/rfq/create-rfq', method: :post, signed: true },
    { name: :execute_quote, path: '/v5/rfq/execute-quote', method: :post, signed: true },
    { name: :get_config, path: '/v5/rfq/config', method: :get, signed: true },
    { name: :get_public_trades, path: '/v5/rfq/public-trades', method: :get, signed: true },
    { name: :get_quotes, path: '/v5/rfq/quote-list', method: :get, signed: true },
    { name: :get_quotes_realtime, path: '/v5/rfq/quote-realtime', method: :get, signed: true },
    { name: :get_rfqs, path: '/v5/rfq/rfq-list', method: :get, signed: true },
    { name: :get_rfqs_realtime, path: '/v5/rfq/rfq-realtime', method: :get, signed: true },
    { name: :get_trade_history, path: '/v5/rfq/trade-list', method: :get, signed: true },
  ].freeze

  method_table.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
