# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::TradeService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::TradeService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  method_table = [
    { name: :amend_order, path: '/v5/order/amend', method: :post, signed: true },
    { name: :batch_amend_orders, path: '/v5/order/amend-batch', method: :post, signed: true },
    { name: :batch_cancel_orders, path: '/v5/order/cancel-batch', method: :post, signed: true },
    { name: :batch_create_orders, path: '/v5/order/create-batch', method: :post, signed: true },
    { name: :cancel_all_orders, path: '/v5/order/cancel-all', method: :post, signed: true },
    { name: :cancel_order, path: '/v5/order/cancel', method: :post, signed: true },
    { name: :create_order, path: '/v5/order/create', method: :post, signed: true },
    { name: :get_execution_history, path: '/v5/execution/list', method: :get, signed: true },
    { name: :get_open_orders, path: '/v5/order/realtime', method: :get, signed: true },
    { name: :get_order_history, path: '/v5/order/history', method: :get, signed: true },
    { name: :get_spot_borrow_quota, path: '/v5/order/spot-borrow-check', method: :get, signed: true },
    { name: :pre_check_order, path: '/v5/order/pre-check', method: :post, signed: true },
    { name: :set_dcp_time_window, path: '/v5/order/disconnected-cancel-all', method: :post, signed: true },
  ].freeze

  method_table.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
