# frozen_string_literal: true

# Smoke tests for Bybit::RestApi::UserService — table-driven assertion that every
# public method dispatches to the correct (path, HTTP method, signed) tuple.
# Auto-generated by tools/gen_service_specs.py; hand-edits are OK but will be
# overwritten if the generator runs again.

RSpec.describe Bybit::RestApi::UserService do
  let(:session) { instance_double(Bybit::Session, public_request: {}, sign_request: {}) }
  let(:svc) { described_class.new(session) }

  # Filled in by the loop below — one row per method the scanner picked up.
  METHOD_TABLE = [
    { name: :create_sub_api_key, path: '/v5/user/create-sub-api', method: :post, signed: true },
    { name: :create_sub_member, path: '/v5/user/create-sub-member', method: :post, signed: true },
    { name: :delete_api_key, path: '/v5/user/delete-api', method: :post, signed: true },
    { name: :delete_sub_api_key, path: '/v5/user/delete-sub-api', method: :post, signed: true },
    { name: :delete_sub_member, path: '/v5/user/del-submember', method: :post, signed: true },
    { name: :frozen_sub_member, path: '/v5/user/frozen-sub-member', method: :post, signed: true },
    { name: :get_affiliate_custom_open_info, path: '/v5/user/aff-customer-info', method: :get, signed: true },
    { name: :get_api_key_info, path: '/v5/user/query-api', method: :get, signed: true },
    { name: :get_member_account_type, path: '/v5/user/get-member-type', method: :get, signed: true },
    { name: :list_escrow_sub_members, path: '/v5/user/escrow_sub_members', method: :get, signed: true },
    { name: :list_referrals, path: '/v5/user/invitation/referrals', method: :get, signed: true },
    { name: :list_sub_api_keys, path: '/v5/user/sub-apikeys', method: :get, signed: true },
    { name: :list_sub_member_uids, path: '/v5/user/query-sub-members', method: :get, signed: true },
    { name: :list_sub_members, path: '/v5/user/submembers', method: :get, signed: true },
    { name: :sign_agreement, path: '/v5/user/agreement', method: :post, signed: true },
    { name: :update_api_key, path: '/v5/user/update-api', method: :post, signed: true },
    { name: :update_sub_api_key, path: '/v5/user/update-sub-api', method: :post, signed: true },
  ].freeze

  METHOD_TABLE.each do |row|
    describe "##{row[:name]}" do
      it "dispatches #{row[:method].upcase} #{row[:path]} (signed=#{row[:signed]})" do
        target = row[:signed] ? :sign_request : :public_request
        expect(session).to receive(target) do |**kw|
          expect(kw[:path]).to eq(row[:path])
          if row[:signed] || row[:method] != :get
            expect(kw[:method]).to eq(row[:method]) if kw.key?(:method)
          end
          {}
        end
        # Supply blank strings for every required keyword arg — the value
        # doesn't matter, we're asserting dispatch, not the wire payload.
        method = svc.method(row[:name])
        required_kw = method.parameters.select { |t, _| t == :keyreq }.map { |_, n| [n, ""] }.to_h
        svc.public_send(row[:name], **required_kw)
      end
    end
  end
end
